services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: flag_user
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: flag_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flag_user -d flag_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Tell the API how to connect to the 'db' service
      DATABASE_URL: postgres://flag_user:supersecretpassword@db:5432/flag_db?sslmode=disable
      REDIS_URL: redis:6379
      ADMIN_API_KEY: my-super-secure-production-key-999
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
